force-app/main/default/objects/Customer_Order__c/Customer_Order__c.object-meta.xml
<CustomObject>
    <label>Customer Order</label>
    <nameField>
        <label>Customer Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
                <default>true</default>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dish__c/Dish__c.object-meta.xml
<CustomObject>
    <label>Dish</label>
    <nameField>
        <label>Dish Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dishes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dish__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Breakfast</fullName>
            </value>
            <value>
                <fullName>Salad</fullName>
            </value>
            <value>
                <fullName>Pizza</fullName>
            </value>
            <value>
                <fullName>Drinks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dish__c/fields/SubCategory__c.field-meta.xml
<CustomField>
    <fullName>SubCategory__c</fullName>
    <label>SubCategory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alcohol</fullName>
            </value>
            <value>
                <fullName>Non-Alcohol</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Customer_Order__c.field-meta.xml
<CustomField>
    <fullName>Customer_Order__c</fullName>
    <label>Customer Order</label>
    <referenceTo>Customer_Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Dish__c.field-meta.xml
<CustomField>
    <fullName>Dish__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dish</label>
    <referenceTo>Dish__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MenuController.cls
public with sharing class MenuController {

    @AuraEnabled(cacheable = true)
    public static Dish__c[] getAllDishes(String category, String subCategory){

        System.debug(category + ' ' + subCategory);

        List<Dish__c> dishes = new List<Dish__c>();

        if(category == 'All'){
            dishes = [SELECT Id, Name, Category__c, SubCategory__c, Price__c, Description__c FROM Dish__c];

        } else if(subCategory == 'All'){
            dishes = [SELECT Id, Name, Category__c, SubCategory__c, Price__c, Description__c FROM Dish__c WHERE Category__c =: category];

        } else {
            dishes = [SELECT Id, Name, Category__c, SubCategory__c, Price__c, Description__c FROM Dish__c WHERE Category__c =: category AND SubCategory__c =: subCategory];

        }

        return dishes ;

    }

    @AuraEnabled
    public static void createOrder(Customer_Order__c order, List<Order_Item__c> items){
        System.debug('Order: ' + order + ' Items: ' +  items);
        order.Status__c = 'Accepted';
        insert order;

        for(Order_Item__c orderItem: items){
            orderItem.Customer_Order__c = order.Id;
        }

        insert items; 
        
    }

    @AuraEnabled(cacheable = true)
    public static Customer_Order__c[] getOrdersByUser(){ // by id
        Id currentUser = UserInfo.getUserId();
        return [SELECT Id, Name FROM Customer_Order__c WHERE OwnerId =: currentUser ];
        
    }

}